### ISSUE TITLE
Get_CurrentBoundingRectangle() in uiautomation.go has some error

### ISSUE THREAD

**Issue by bjwjs** [auuunya/go-element#1]
Get_CurrentBoundingRectangle() in uiautomation.go has some error, correct as below：
func (v *IUIAutomationElement) Get_CurrentBoundingRectangle() *TagRect {
	var retVal TagRect
	syscall.SyscallN(
		(*IUIAutomationElementVtbl)(unsafe.Pointer(v.vtbl)).Get_CurrentBoundingRectangle,
		uintptr(unsafe.Pointer(v)),
		uintptr(unsafe.Pointer(&retVal)),
	)
	return &retVal
}

**Comment by auuunya** [comment]
thanks.
It's true that this problem exists.
If you'd like to join us, you can submit PR
